# Generated by Django 2.2.6 on 2020-05-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Husband',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('religion', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(max_length=100, null=True)),
                ('marrital', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('adhar', models.CharField(max_length=100, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('religion', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(max_length=100, null=True)),
                ('marrital', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('adhar', models.CharField(max_length=100, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100, null=True)),
                ('name2', models.CharField(max_length=100, null=True)),
                ('name3', models.CharField(max_length=100, null=True)),
                ('address1', models.CharField(max_length=100, null=True)),
                ('address2', models.CharField(max_length=100, null=True)),
                ('address3', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marriage_date', models.DateField(null=True)),
                ('reg_date', models.DateField(null=True)),
                ('husband', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marriage.Husband')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marriage.Signup')),
                ('wife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marriage.Wife')),
                ('witness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marriage.Witness')),
            ],
        ),
    ]
