# Generated by Django 2.2.6 on 2020-05-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0002_husband_registration_wife_witness'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='u_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
