# Generated by Django 2.2.6 on 2020-05-31 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0005_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=100, null=True)),
                ('marriage_date', models.DateField(null=True)),
                ('reg_date', models.DateField(null=True)),
                ('husband', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marriage.Husband')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marriage.Status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marriage.Signup')),
                ('wife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marriage.Wife')),
                ('witness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marriage.Witness')),
            ],
        ),
    ]
