# Generated by Django 2.2.6 on 2020-06-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0006_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='remark',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
