# Generated by Django 2.2.6 on 2020-06-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0007_registration_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='report_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
